execution:
- executor: selenium
  scenario: open_page

scenarios:
  open_page:
    browser: Chrome
    timeout: 10s
    think-time: 3s
    requests:
    - url: http://blazedemo.com


-- 
- hosts: AppServer 
 become: yes 
 tasks: 
 - name: Installs nginx web server 
 Apt: name: nginx state: started update_cache: true 
 notify: 
 - start nginx 
 handlers: 
 - name: start nginx 
 service: 
 name: nginx 
 state: started 
Let’s break the code into segments for a better understanding. 
--- 







#!/bin/bash




let RESULT1=$1+$2


echo $1+$2=$RESULT1 ' -> # let RESULT1=$1+$2'


declare -i RESULT2


RESULT2=$1+$2


echo $1+$2=$RESULT2 ' -> # declare -i RESULT2; RESULT2=$1+$2'


echo $1+$2=$(($1 + $2)) ' -> # $(($1 + $2))'
